-- Disable Row-Level Security (RLS) for tests
ALTER TABLE artist_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE fan_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE releases DISABLE ROW LEVEL SECURITY;
ALTER TABLE tracks DISABLE ROW LEVEL SECURITY; 